// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mapo.proto

package mapo

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClientState struct {
	Frozen               bool     `protobuf:"varint,1,opt,name=frozen,proto3" json:"frozen,omitempty"`
	LatestEpoch          uint64   `protobuf:"varint,2,opt,name=latestEpoch,proto3" json:"latestEpoch,omitempty"`
	EpochSize            uint64   `protobuf:"varint,3,opt,name=epochSize,proto3" json:"epochSize,omitempty"`
	ClientIdentifier     string   `protobuf:"bytes,4,opt,name=ClientIdentifier,proto3" json:"ClientIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type ConsensusState struct {
	Epoch                uint64        `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validators           *ValidatorSet `protobuf:"bytes,2,opt,name=validators,proto3" json:"validators,omitempty"`
	CommitmentRoot       []byte        `protobuf:"bytes,3,opt,name=commitmentRoot,proto3" json:"commitmentRoot,omitempty"`
	Timestamp            time.Time     `protobuf:"bytes,4,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{1}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusState.Unmarshal(m, b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return xxx_messageInfo_ConsensusState.Size(m)
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type ValidatorSet struct {
	PairKeys             []*PairKey `protobuf:"bytes,1,rep,name=pairKeys,proto3" json:"pairKeys,omitempty"`
	Weights              []uint64   `protobuf:"varint,2,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{2}
}
func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSet.Unmarshal(m, b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
}
func (m *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(m, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return xxx_messageInfo_ValidatorSet.Size(m)
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

type PairKey struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	G2PubKey             []byte   `protobuf:"bytes,2,opt,name=G2PubKey,proto3" json:"G2PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairKey) Reset()         { *m = PairKey{} }
func (m *PairKey) String() string { return proto.CompactTextString(m) }
func (*PairKey) ProtoMessage()    {}
func (*PairKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{3}
}
func (m *PairKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairKey.Unmarshal(m, b)
}
func (m *PairKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairKey.Marshal(b, m, deterministic)
}
func (m *PairKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairKey.Merge(m, src)
}
func (m *PairKey) XXX_Size() int {
	return xxx_messageInfo_PairKey.Size(m)
}
func (m *PairKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PairKey.DiscardUnknown(m)
}

var xxx_messageInfo_PairKey proto.InternalMessageInfo

type Misbehaviour struct {
	Header1              *Header  `protobuf:"bytes,1,opt,name=header1,proto3" json:"header1,omitempty"`
	Header2              *Header  `protobuf:"bytes,2,opt,name=header2,proto3" json:"header2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{4}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Misbehaviour.Unmarshal(m, b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return xxx_messageInfo_Misbehaviour.Size(m)
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

type Header struct {
	*SignedHeader        `protobuf:"bytes,1,opt,name=signedHeader,proto3,embedded=signedHeader" json:"signedHeader,omitempty"`
	CommitmentRoot       []byte   `protobuf:"bytes,2,opt,name=commitmentRoot,proto3" json:"commitmentRoot,omitempty"`
	Identifier           string   `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{5}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

type SignedHeader struct {
	ParentHash           []byte   `protobuf:"bytes,1,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	TxRoot               []byte   `protobuf:"bytes,3,opt,name=txRoot,proto3" json:"txRoot,omitempty"`
	ReceiptRoot          []byte   `protobuf:"bytes,4,opt,name=receiptRoot,proto3" json:"receiptRoot,omitempty"`
	Timestamp            uint64   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GasLimit             uint64   `protobuf:"varint,6,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed              uint64   `protobuf:"varint,7,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Nonce                uint64   `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Bloom                []byte   `protobuf:"bytes,9,opt,name=bloom,proto3" json:"bloom,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,10,opt,name=extraData,proto3" json:"extraData,omitempty"`
	MixDigest            []byte   `protobuf:"bytes,11,opt,name=mixDigest,proto3" json:"mixDigest,omitempty"`
	BaseFee              uint64   `protobuf:"varint,12,opt,name=baseFee,proto3" json:"baseFee,omitempty"`
	Number               uint64   `protobuf:"varint,13,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedHeader) Reset()         { *m = SignedHeader{} }
func (m *SignedHeader) String() string { return proto.CompactTextString(m) }
func (*SignedHeader) ProtoMessage()    {}
func (*SignedHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{6}
}
func (m *SignedHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedHeader.Unmarshal(m, b)
}
func (m *SignedHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedHeader.Marshal(b, m, deterministic)
}
func (m *SignedHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedHeader.Merge(m, src)
}
func (m *SignedHeader) XXX_Size() int {
	return xxx_messageInfo_SignedHeader.Size(m)
}
func (m *SignedHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedHeader proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.mapo.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.mapo.v1.ConsensusState")
	proto.RegisterType((*ValidatorSet)(nil), "ibc.lightclients.mapo.v1.ValidatorSet")
	proto.RegisterType((*PairKey)(nil), "ibc.lightclients.mapo.v1.PairKey")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.mapo.v1.Misbehaviour")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.mapo.v1.Header")
	proto.RegisterType((*SignedHeader)(nil), "ibc.lightclients.mapo.v1.SignedHeader")
}

func init() { proto.RegisterFile("mapo.proto", fileDescriptor_a45068151aeb9ae4) }

var fileDescriptor_a45068151aeb9ae4 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcb, 0x6e, 0xd4, 0x30,
	0x14, 0x6d, 0x3a, 0xe9, 0x3c, 0x9c, 0x50, 0x21, 0x0b, 0x21, 0x6b, 0x84, 0x3a, 0x43, 0x17, 0xd5,
	0x88, 0x45, 0xaa, 0x86, 0x5d, 0x25, 0x36, 0xd3, 0x07, 0x45, 0x05, 0xa9, 0xf2, 0x00, 0x0b, 0x76,
	0xce, 0xe4, 0x36, 0x63, 0x69, 0x12, 0x47, 0xb1, 0xa7, 0xb4, 0xfd, 0x02, 0x16, 0x2c, 0xd8, 0xb1,
	0x65, 0xc9, 0xa7, 0xb0, 0xe4, 0x0b, 0x0a, 0x9f, 0xc0, 0x27, 0x20, 0xdb, 0xc9, 0x24, 0x85, 0x0e,
	0x62, 0x97, 0x73, 0xce, 0xbd, 0xf6, 0xf1, 0x7d, 0x04, 0xa1, 0x94, 0xe5, 0x22, 0xc8, 0x0b, 0xa1,
	0x04, 0x26, 0x3c, 0x9a, 0x06, 0x73, 0x9e, 0xcc, 0xd4, 0x74, 0xce, 0x21, 0x53, 0x32, 0x30, 0xe2,
	0xc5, 0x5e, 0x7f, 0x90, 0x08, 0x91, 0xcc, 0x61, 0xd7, 0xc4, 0x45, 0x8b, 0xf3, 0x5d, 0xc5, 0x53,
	0x90, 0x8a, 0xa5, 0xb9, 0x4d, 0xed, 0x6f, 0x25, 0x22, 0x11, 0xe6, 0x73, 0xf7, 0xf6, 0x97, 0xd5,
	0xb7, 0x3f, 0x3b, 0xc8, 0x3b, 0x30, 0x87, 0x4e, 0x14, 0x53, 0x80, 0x1f, 0xa2, 0xf6, 0x79, 0x21,
	0xae, 0x21, 0x23, 0xce, 0xd0, 0x19, 0x75, 0x69, 0x89, 0xf0, 0x10, 0x79, 0x73, 0xa6, 0x40, 0xaa,
	0xa3, 0x5c, 0x4c, 0x67, 0x64, 0x7d, 0xe8, 0x8c, 0x5c, 0xda, 0xa4, 0xf0, 0x23, 0xd4, 0x03, 0xfd,
	0x31, 0xe1, 0xd7, 0x40, 0x5a, 0x46, 0xaf, 0x09, 0xfc, 0x04, 0xdd, 0xb7, 0xd7, 0xbc, 0x88, 0x21,
	0x53, 0xfc, 0x9c, 0x43, 0x41, 0xdc, 0xa1, 0x33, 0xea, 0xd1, 0xbf, 0xf8, 0x7d, 0xf7, 0xc3, 0x97,
	0xc1, 0xda, 0xf6, 0x4f, 0x07, 0x6d, 0x1e, 0x88, 0x4c, 0x42, 0x26, 0x17, 0xd2, 0x9a, 0x7b, 0x80,
	0x36, 0xcc, 0x89, 0xc6, 0x9b, 0x4b, 0x2d, 0xc0, 0xc7, 0x08, 0x5d, 0xb0, 0x39, 0x8f, 0x99, 0x12,
	0x85, 0x34, 0xce, 0xbc, 0x70, 0x27, 0x58, 0x55, 0xb2, 0xe0, 0x6d, 0x15, 0x3b, 0x01, 0x45, 0x1b,
	0x99, 0x78, 0x07, 0x6d, 0x4e, 0x45, 0x9a, 0x72, 0x95, 0x42, 0xa6, 0xa8, 0x10, 0xca, 0xbc, 0xc2,
	0xa7, 0x7f, 0xb0, 0x78, 0x8c, 0x7a, 0xcb, 0x2a, 0x9b, 0x37, 0x78, 0x61, 0x3f, 0xb0, 0x7d, 0x08,
	0xaa, 0x3e, 0x04, 0xaf, 0xab, 0x88, 0x71, 0xf7, 0xdb, 0xcd, 0x60, 0xed, 0xd3, 0x8f, 0x81, 0x43,
	0xeb, 0xb4, 0xf2, 0x89, 0x29, 0xf2, 0x9b, 0x6e, 0xf0, 0x33, 0xd4, 0xcd, 0x19, 0x2f, 0x4e, 0xe1,
	0x4a, 0x12, 0x67, 0xd8, 0x1a, 0x79, 0xe1, 0xe3, 0xd5, 0xef, 0x38, 0xb3, 0x91, 0x74, 0x99, 0x82,
	0x09, 0xea, 0xbc, 0x07, 0x1d, 0xaa, 0xab, 0xd0, 0x1a, 0xb9, 0xb4, 0x82, 0xe5, 0x75, 0x47, 0xa8,
	0x53, 0x26, 0xe9, 0x50, 0x16, 0xc7, 0x05, 0x48, 0x69, 0x6a, 0xd9, 0xa3, 0x15, 0xc4, 0x7d, 0xd4,
	0x7d, 0x1e, 0x9e, 0x2d, 0xa2, 0x53, 0xb8, 0x32, 0xb5, 0xf4, 0xe9, 0x12, 0x97, 0xc7, 0x7c, 0x74,
	0x90, 0xff, 0x8a, 0xcb, 0x08, 0x66, 0xec, 0x82, 0x8b, 0x45, 0x81, 0xf7, 0x51, 0x67, 0x06, 0x2c,
	0x86, 0x62, 0xcf, 0x1c, 0xe6, 0x85, 0xc3, 0xd5, 0xae, 0x4f, 0x4c, 0x20, 0xad, 0x12, 0xea, 0xdc,
	0xb0, 0xec, 0xdc, 0x7f, 0xe7, 0x86, 0xa5, 0x9d, 0xaf, 0x0e, 0x6a, 0x5b, 0x05, 0x9f, 0x21, 0x5f,
	0xf2, 0x24, 0x83, 0xd8, 0xe2, 0xd2, 0xcd, 0x3f, 0x66, 0x61, 0xd2, 0x88, 0x1e, 0xbb, 0xdf, 0x6f,
	0x06, 0x0e, 0xbd, 0x75, 0xc2, 0x1d, 0x33, 0xb1, 0x7e, 0xe7, 0x4c, 0x6c, 0x21, 0xc4, 0xeb, 0xc1,
	0x6e, 0x99, 0x92, 0x36, 0x98, 0xd2, 0xea, 0xaf, 0x75, 0xe4, 0x37, 0xaf, 0xd4, 0x69, 0x39, 0x2b,
	0x20, 0x53, 0x27, 0x4c, 0xda, 0xa9, 0xf6, 0x69, 0x83, 0xc1, 0x18, 0xb9, 0x45, 0x7d, 0xa9, 0xf9,
	0xd6, 0x1b, 0xaa, 0x2e, 0x1b, 0xe3, 0x59, 0x22, 0xbd, 0xa1, 0x05, 0x4c, 0x81, 0xe7, 0xd6, 0xa7,
	0x6b, 0xc4, 0x26, 0xa5, 0x37, 0xb4, 0x1e, 0xdc, 0x0d, 0xbb, 0xa1, 0x4b, 0x42, 0x37, 0x3e, 0x61,
	0xf2, 0x25, 0x4f, 0xb9, 0x22, 0x6d, 0x23, 0x2e, 0xb1, 0x1e, 0x97, 0x84, 0xc9, 0x37, 0x12, 0x62,
	0xd2, 0x31, 0x52, 0x05, 0xf5, 0x4a, 0x66, 0x22, 0x9b, 0x02, 0xe9, 0xda, 0x95, 0x34, 0x40, 0xb3,
	0xd1, 0x5c, 0x88, 0x94, 0xf4, 0x8c, 0x0b, 0x0b, 0xcc, 0x1f, 0xe2, 0x52, 0x15, 0xec, 0x90, 0x29,
	0x46, 0x90, 0x51, 0x6a, 0x42, 0xab, 0x29, 0xbf, 0x3c, 0xe4, 0x09, 0x48, 0x45, 0x3c, 0xab, 0x2e,
	0x09, 0xed, 0x20, 0x62, 0x12, 0x8e, 0x01, 0x88, 0x6f, 0x1d, 0x94, 0x50, 0xd7, 0x23, 0x5b, 0xa4,
	0x11, 0x14, 0xe4, 0x9e, 0x11, 0x4a, 0x64, 0x4b, 0x3e, 0x6e, 0xbf, 0x73, 0x75, 0xb3, 0xa3, 0xb6,
	0xd9, 0xcc, 0xa7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x12, 0xe5, 0xaa, 0xda, 0x57, 0x05, 0x00,
	0x00,
}
