// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mapo.proto

package mapo

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClientState struct {
	Frozen               bool     `protobuf:"varint,1,opt,name=frozen,proto3" json:"frozen,omitempty"`
	LatestEpoch          uint64   `protobuf:"varint,2,opt,name=latestEpoch,proto3" json:"latestEpoch,omitempty"`
	EpochSize            uint64   `protobuf:"varint,3,opt,name=epochSize,proto3" json:"epochSize,omitempty"`
	ClientIdentifier     string   `protobuf:"bytes,4,opt,name=ClientIdentifier,proto3" json:"ClientIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type ConsensusState struct {
	Epoch                uint64        `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Validators           *ValidatorSet `protobuf:"bytes,2,opt,name=validators,proto3" json:"validators,omitempty"`
	CommitmentRoot       []byte        `protobuf:"bytes,3,opt,name=commitmentRoot,proto3" json:"commitmentRoot,omitempty"`
	Timestamp            time.Time     `protobuf:"bytes,4,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{1}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusState.Unmarshal(m, b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return xxx_messageInfo_ConsensusState.Size(m)
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type ValidatorSet struct {
	PairKeys             []*PairKey `protobuf:"bytes,1,rep,name=pairKeys,proto3" json:"pairKeys,omitempty"`
	Weights              []uint64   `protobuf:"varint,2,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{2}
}
func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSet.Unmarshal(m, b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
}
func (m *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(m, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return xxx_messageInfo_ValidatorSet.Size(m)
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

type PairKey struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	G2PubKey             []byte   `protobuf:"bytes,2,opt,name=G2PubKey,proto3" json:"G2PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairKey) Reset()         { *m = PairKey{} }
func (m *PairKey) String() string { return proto.CompactTextString(m) }
func (*PairKey) ProtoMessage()    {}
func (*PairKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a45068151aeb9ae4, []int{3}
}
func (m *PairKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairKey.Unmarshal(m, b)
}
func (m *PairKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairKey.Marshal(b, m, deterministic)
}
func (m *PairKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairKey.Merge(m, src)
}
func (m *PairKey) XXX_Size() int {
	return xxx_messageInfo_PairKey.Size(m)
}
func (m *PairKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PairKey.DiscardUnknown(m)
}

var xxx_messageInfo_PairKey proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.mapo.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.mapo.v1.ConsensusState")
	proto.RegisterType((*ValidatorSet)(nil), "ibc.lightclients.mapo.v1.ValidatorSet")
	proto.RegisterType((*PairKey)(nil), "ibc.lightclients.mapo.v1.PairKey")
}

func init() { proto.RegisterFile("mapo.proto", fileDescriptor_a45068151aeb9ae4) }

var fileDescriptor_a45068151aeb9ae4 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x6e, 0xd4, 0x30,
	0x14, 0xac, 0xd9, 0xb0, 0xdd, 0x7d, 0x59, 0x55, 0xc8, 0x42, 0x28, 0x8a, 0x40, 0x09, 0x3d, 0x54,
	0x11, 0x07, 0x57, 0x84, 0x1b, 0x12, 0x97, 0xad, 0x0a, 0x42, 0xbd, 0x54, 0x5e, 0xc4, 0x81, 0x9b,
	0x93, 0xbc, 0x4d, 0x2d, 0x25, 0x71, 0x14, 0x7b, 0x8b, 0xda, 0x2f, 0xe0, 0xc8, 0x8d, 0x2b, 0x9f,
	0xc3, 0x57, 0x00, 0x9f, 0x82, 0x62, 0x27, 0xe9, 0x8a, 0xaa, 0xb7, 0xcc, 0x7b, 0x33, 0xcf, 0x33,
	0x13, 0x80, 0x5a, 0xb4, 0x8a, 0xb5, 0x9d, 0x32, 0x8a, 0x06, 0x32, 0xcb, 0x59, 0x25, 0xcb, 0x2b,
	0x93, 0x57, 0x12, 0x1b, 0xa3, 0x99, 0x5d, 0x5e, 0xbf, 0x0e, 0xa3, 0x52, 0xa9, 0xb2, 0xc2, 0x53,
	0xcb, 0xcb, 0x76, 0xdb, 0x53, 0x23, 0x6b, 0xd4, 0x46, 0xd4, 0xad, 0x93, 0x86, 0x2f, 0xa6, 0x4d,
	0xa9, 0x4a, 0x65, 0x81, 0xfd, 0x72, 0xeb, 0xe3, 0x1f, 0x04, 0xfc, 0x33, 0x7b, 0x73, 0x63, 0x84,
	0x41, 0xfa, 0x0c, 0xe6, 0xdb, 0x4e, 0xdd, 0x62, 0x13, 0x90, 0x98, 0x24, 0x0b, 0x3e, 0x20, 0x1a,
	0x83, 0x5f, 0x09, 0x83, 0xda, 0x9c, 0xb7, 0x2a, 0xbf, 0x0a, 0x1e, 0xc5, 0x24, 0xf1, 0xf8, 0xfe,
	0x88, 0x3e, 0x87, 0x25, 0xf6, 0x1f, 0x1b, 0x79, 0x8b, 0xc1, 0xcc, 0xee, 0xef, 0x06, 0xf4, 0x15,
	0x3c, 0x71, 0xcf, 0x7c, 0x2c, 0xb0, 0x31, 0x72, 0x2b, 0xb1, 0x0b, 0xbc, 0x98, 0x24, 0x4b, 0x7e,
	0x6f, 0xfe, 0xd6, 0xfb, 0xf6, 0x33, 0x3a, 0x38, 0xfe, 0x4b, 0xe0, 0xe8, 0x4c, 0x35, 0x1a, 0x1b,
	0xbd, 0xd3, 0xce, 0xdc, 0x53, 0x78, 0x6c, 0x2f, 0x5a, 0x6f, 0x1e, 0x77, 0x80, 0xbe, 0x07, 0xb8,
	0x16, 0x95, 0x2c, 0x84, 0x51, 0x9d, 0xb6, 0xce, 0xfc, 0xf4, 0x84, 0x3d, 0xd4, 0x18, 0xfb, 0x3c,
	0x72, 0x37, 0x68, 0xf8, 0x9e, 0x92, 0x9e, 0xc0, 0x51, 0xae, 0xea, 0x5a, 0x9a, 0x1a, 0x1b, 0xc3,
	0x95, 0x32, 0x36, 0xc5, 0x8a, 0xff, 0x37, 0xa5, 0x6b, 0x58, 0x4e, 0x25, 0xdb, 0x0c, 0x7e, 0x1a,
	0x32, 0xf7, 0x1b, 0xd8, 0x58, 0x36, 0xfb, 0x34, 0x32, 0xd6, 0x8b, 0x5f, 0xbf, 0xa3, 0x83, 0xef,
	0x7f, 0x22, 0xc2, 0xef, 0x64, 0x43, 0xc4, 0x1a, 0x56, 0xfb, 0x6e, 0xe8, 0x3b, 0x58, 0xb4, 0x42,
	0x76, 0x17, 0x78, 0xa3, 0x03, 0x12, 0xcf, 0x12, 0x3f, 0x7d, 0xf9, 0x70, 0x8e, 0x4b, 0xc7, 0xe4,
	0x93, 0x84, 0x06, 0x70, 0xf8, 0x15, 0x7b, 0x6a, 0xdf, 0xc2, 0x2c, 0xf1, 0xf8, 0x08, 0x87, 0xe7,
	0xce, 0xe1, 0x70, 0x10, 0xf5, 0x54, 0x51, 0x14, 0x1d, 0x6a, 0x6d, 0xbb, 0x5c, 0xf2, 0x11, 0xd2,
	0x10, 0x16, 0x1f, 0xd2, 0xcb, 0x5d, 0x76, 0x81, 0x37, 0xb6, 0xcb, 0x15, 0x9f, 0xb0, 0x3b, 0xb3,
	0x9e, 0x7f, 0xf1, 0x7a, 0x0f, 0xd9, 0xdc, 0x86, 0x7d, 0xf3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x31,
	0xfe, 0xa2, 0x55, 0xa9, 0x02, 0x00, 0x00,
}
